#
# Makefile for the lguest vector.
#



obj-$(CONFIG_ARM_LGUEST_GUEST)	:= lguest_device.o lguest_privileged_ops_init.o board-lguest.o proc-lguest.o	\
									 lguest-entry-armv.o  lguest-entry-common.o	 boot.o 


